.docker_build:
  image: "docker:19.03.11"
  stage: .pre
  services:
    - docker:19.03.11-dind
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd test/ci/${IMAGE_NAME}/
    - docker build --no-cache -t registry.gitlab.com/akantu/akantu/${IMAGE_NAME} .
    - docker push registry.gitlab.com/akantu/akantu/${IMAGE_NAME}
  rules:
    - changes:
        - test/ci/${IMAGE_NAME}/*

# ------------------------------------------------------------------------------
.cache_build:
  variables:
    CCACHE_BASEDIR: ${CI_PROJECT_DIR}/
    CCACHE_DIR: ${CI_PROJECT_DIR}/.ccache
    CCACHE_MAXSIZE: 1Gi
  cache:
    key: ${output}_${BUILD_TYPE}
    policy: pull-push
    paths:
      - .ccache/
      - third-party/google-test
      - third-party/pybind11
  before_script:
    - ccache --zero-stats || true
  after_script:
    - ccache --show-stats || true

# ------------------------------------------------------------------------------
.image_debian_bullseye:
  image: registry.gitlab.com/akantu/akantu/debian:bullseye

.image_ubuntu_lts:
  image: registry.gitlab.com/akantu/akantu/ubuntu:lts

.image_manylinux:
  image: registry.gitlab.com/akantu/akantu/manylinux:2010_x86_64

# ------------------------------------------------------------------------------
.compiler_gcc:
  variables:
    CC: /usr/lib/ccache/gcc
    CXX: /usr/lib/ccache/g++
    FC: gfortran
    GCOV_EXECUTABLE: gcov

.compiler_clang:
  variables:
    CC: /usr/lib/ccache/clang
    CXX: /usr/lib/ccache/clang++
    FC: gfortran
    GCOV_EXECUTABLE: llvm-cov gcov

.build_coverage:
  variables:
    TEST_EXAMPLES: "FALSE"
    BUILD_TYPE: "Coverage"

.build_release:
  variables:
    TEST_EXAMPLES: "TRUE"
    BUILD_TYPE: "Release"

.build_valgrind:
  variables:
    TEST_EXAMPLES: "FALSE"
    BUILD_TYPE: "Valgrind"

# ------------------------------------------------------------------------------
.debian_bullseye_gcc:
  variables:
    output: debian_bullseye_gcc
  extends:
    - .compiler_gcc
    - .image_debian_bullseye
    - .cache_build

.debian_bullseye_clang:
  variables:
    output: debian_bullseye_clang
  extends:
    - .compiler_clang
    - .image_debian_bullseye
    - .cache_build

.ubuntu_lts_gcc:
  variables:
    output: ubuntu_lts_gcc
  extends:
    - .compiler_gcc
    - .image_ubuntu_lts
    - .cache_build

.manylinux_2010_x64_gcc:
  variables:
    output: manylinux_2010_x64_gcc
  extends:
    - .compiler_gcc
    - .image_manylinux
    - .cache_build
